apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-app
  labels:
    app: nginx-deployment-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment-app
  template:
    metadata:
      labels:
        app: nginx-deployment-app
    spec:
      containers:
      - name: nginx-app
        image: hillarydevops/nginx-deployment
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
  namespace: deployments
spec:
  selector:
    app: nginx-deployment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
